### ISSUE TITLE
Examples: Interface from Python to C++

### ISSUE THREAD

**Issue by Deejep** [TNG/boost-python-examples#15]
Would you add some examples of Python functions calls from C++ code ?

**Comment by waldeyr** [comment]
I would like It a lot of some examples too

Em 23 de jun de 2017 12:38 AM, "Deejep" <notifications@github.com> escreveu:

**Comment by Achimh3011** [comment]
Running a file is shown in [the embedding example](https://github.com/TNG/boost-python-examples/blob/master/10-Embedding/embedding.cpp#L27). 

For more possibilities see [the boost:python docs](http://www.boost.org/doc/libs/develop/libs/python/doc/html/tutorial/tutorial/embedding.html#tutorial.embedding.using_the_interpreter).

If you want to find the callable by searching the python interpreter from C++ side, see [the auto-instantiation example](https://github.com/TNG/boost-python-examples/blob/master/13-AutoInstantiation/auto_instance.cpp#L37). Yes, that line calls the class object thus creating an instance object.
