### ISSUE TITLE
PYTHON_VERSION_SUFFIX issue

### ISSUE THREAD

**Issue by ivanstepanovftw** [TNG/boost-python-examples#26]
i think it must be
PYTHON_VERSION_SUFFIX=3
instead of
PYTHON_VERSION_SUFFIX=-py3
-py3 working, but Boost returns /usr/lib/libboost_python.so that usually links to /usr/lib/libboost_python2.so.

**Comment by ivanstepanovftw** [comment]
Manjaro

**Comment by mahaidong** [comment]
in mojave, when using brew python3 as default python:

```
brew install boost-python3
mkdir build && cd build
cmake ..
make
make test
```

it works for me.

**Comment by Achimh3011** [comment]
@ivanstepanovftw You can add a test for manjaro to `build.sh` and raise a PR.

**Comment by ivanstepanovftw** [comment]
> @ivanstepanovftw You can add a test for manjaro to `build.sh` and raise a PR.


Maybe later, thanks
