### ISSUE TITLE
Build instructions for inclusion in existing project

### ISSUE THREAD

**Issue by tcwalther** [TNG/boost-python-examples#3]
Hi Achim,

This is a great tutorial, thank you so much for it. I'm currently in the process of rewriting a small portion of my (large) Python codebase in C++, and am wondering how to best configure CMake for that. I've noticed that you copy all your python scripts into the build directory, which for my use case is probably a bit inconvenient - my project is mainly Python, and only one `foo/bar.py` should be replaced by Boost.Python C++ code (so far). Therefore, I'd prefer to do an in-place build.

Do you have any experience with, or best-practice recommendations for this?

Thanks,
Thomas

**Comment by Achimh3011** [comment]
Sorry for not answering - I cannot help you. The projects I used boost::python in were not using CMake, I just started using it for the tutorial. 

As it is not a code issue and nobody else answered, I close the issue now.
