### ISSUE TITLE
__Py_tracemalloc_config

### ISSUE THREAD

**Issue by chemiskyy** [TNG/boost-python-examples#35]
I am trying to use boost-python3 and get the following error while running tests. I got exactly the same one when trying to test my own library using boost-python3
I suspect that is is due to boost-python3 built with python 3.8.2 using homebrew, while the standard brew python3 version is 3.7.7 

Traceback (most recent call last):
  File "hello.py", line 3, in <module>
    import hello
ImportError: dlopen(/scratch/source/boost-python-examples-master/build/01-HelloWorld/hello.so, 2): Symbol not found: __Py_tracemalloc_config
  Referenced from: /usr/local/opt/boost-python3/lib/libboost_python38.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python3/lib/libboost_python38.dylib
<end of output>
Test time =   0.03 sec

**Comment by Achimh3011** [comment]
Looks like a mismatch between version used for compilation end for execution. Full log of the build would be helpful.

**Comment by chemiskyy** [comment]
Hi Achimh thanks for your reply. It was indeed Boost was compiled against python 3.8.2 and I used Python 3.7.7. I solved it using the same Python version. However most of test fails with Python 3.8.2 I will investigate this more. Here is the log file of the tests

[LastTest.log](https://github.com/TNG/boost-python-examples/files/4558389/LastTest.log)

**Comment by chemiskyy** [comment]
My bad, on MAC OSX Mojave, since boost-python3 using Home-brew is compiled against Python version 3.8.2, I used pyenv to set the same version. 
Might be useful to specify that:

`env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.8.2 `

will install the dynamic python library
In the Cmake command I manually added the path to the correct library: and 100% test passed. 

`cmake .. -DCMAKE_PREFIX_PATH=/Users/ychemisky/.pyenv/versions/3.8.2 -DPYTHON_LIBRARY=/Users/ychemisky/.pyenv/versions/3.8.2/lib/lib/libpython3.8.dylib`

and 100% test passed. you can catch the prefix path if python env is global using:

```
PYTHON_PATH = $(python -c "import sys; print(sys.prefix)")
PYTHON_MAJOR = $(python -c "import sys; print(sys.version_info[0])")
PYTHON_MINOR = $(python -c "import sys; print(sys.version_info[1])")
PYTHON_LIBS = ${PYTHON_PATH}/Python.framework/Versions/${PYTHON_MAJOR}.${PYTHON_MINOR}/lib/libpython${PYTHON_MAJOR}.${PYTHON_MINOR}.dylib
cmake .. -DCMAKE_PREFIX_PATH=${PYTHON_PATH} -DPYTHON_LIBRARY=${PYTHON_LIBS}
```
