### ISSUE TITLE
04-ClassMembers met UnicodeEncodeError

### ISSUE THREAD

**Issue by hanbaobao2005** [TNG/boost-python-examples#6]
![20151203003258](https://cloud.githubusercontent.com/assets/1937472/11552791/9040f832-9956-11e5-8fa3-5d8e411df2cf.png)

MAC:10.11.1
IDE: Sublime text3
Python: Python 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) 
GCC:GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

Code: in member.py caused this issue:
m1.name = "Günther"

Python Error code:
name = Pavel
name = Traceback (most recent call last):
  File "/Users/kevin/Desktop/pythonc++/build/04-ClassMembers/member.py", line 8, in <module>
    print ("name =",m1.name)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 1: ordinal not in range(128)

Also, I'm looking for the way to fix this error.

**Comment by Achimh3011** [comment]
Fixed by merging #8
