### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by Sasszem** [TNG/boost-python-examples#9]
I've built this project via the **newest boost and cmake**, using **`build.sh`**. I've tried to run them but even the first failed with error:
```
$python hello.py 
Traceback (most recent call last):
  File "hello.py", line 3, in <module>
    import hello
  File "<path>/hello.py", line 4, in <module>
    print (hello.greet())

```

Why doesn't it work?

**Comment by Achimh3011** [comment]
The actual error message is missing. Can you include it? Also, what kind of system are you doing this on? OSX? Linux?

**Comment by Sasszem** [comment]
I'm using Ubuntu 16.04, 64 bit version.
The error(how could I omit it?):
`AttributeError: 'module' object has no attribute 'greet'`
